icon: assets/dev/icon.png
summary: A proxy client
group: Application/Proxy
vendor: 5V Network LLC                                                                                                                                                                    
packager: 5V Network LLC
packagerEmail: contactvproxy@proton.me
url: https://vx.5vnetwork.com
license: Commercial
display_name: VX

postinstall_scripts:
  - chmod +x /usr/share/vxproxyclient/data/flutter_assets/packages/tm_linux/assets/x
  - echo "Installed VX"
  #- echo "VX requires root privileges to function properly"
  #- echo "Setting up network permissions..."
  #- setcap cap_net_admin,cap_net_raw,cap_dac_override+ep /usr/bin/vx

postuninstall_scripts:
  - echo "VX has been removed from your system"

keywords:
  - VPN
  - Proxy
  - Network
  - Security
  - Tunneling
  - Privacy
  - Internet
  - Connection
  - Firewall
  - Bypass
  - GFW

generic_name: VX

categories:
  - Network
  - Proxy

startup_notify: true

supported_mime_type:
  - x-scheme-handler/vx # my_custom_scheme:/...
# You can also specify [metainfo](https://freedesktop.org/software/appstream/docs/chap-Quickstart.html) file
# which contains metadata of the app.
# metainfo: linux/packaging/myappid.appdata.xml