display_name: VX
package_name: vx
maintainer:
  name: 5vnetworkllc
  email: contactvproxy@proton.me
priority: optional
section: net

installed_size: 6604
essential: false
icon: assets/dev/icon.png

postinstall_scripts:
  - chmod +x /usr/share/vxproxyclient/data/flutter_assets/packages/tm_linux/assets/x
  - echo "Installed VX"
  #- echo "VX requires root privileges to function properly"
  #- echo "Setting up network permissions..."
  #- setcap cap_net_admin,cap_net_raw,cap_dac_override+ep /usr/bin/vx 
  #- echo "Installing PolicyKit policy..."
  #- cp /usr/share/polkit-1/actions/com.5vnetwork.vx.policy /usr/share/polkit-1/actions/ || echo "PolicyKit policy installation failed"
postuninstall_scripts:
  - echo "VX has been removed from your system"
    # build-packages:
    #   - libsecret-1-dev
    #   - libjsoncpp-dev
    # stage-packages:
    #   - libsecret-1-0
    #   - libjsoncpp-dev
keywords:
  - VPN
  - Proxy
  - Network
  - Security
  - Tunneling
  - Privacy
  - Internet
  - Connection
  - Firewall
  - Bypass
  - GFW

categories:
  - Network
  - Proxy

startup_notify: true

supported_mime_type:
  - x-scheme-handler/vx # my_custom_scheme:/...

# You can also specify [metainfo](https://freedesktop.org/software/appstream/docs/chap-Quickstart.html) file
# which contains metadata of the app.
# metainfo: linux/packaging/myappid.appdata.xml